# Generated by Django 5.1.1 on 2024-09-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMINxCOMENTARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
                ('id_comentario_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comentario')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='administrado',
            field=models.ManyToManyField(blank=True, through='posts.ADMINxCOMENTARIO', to='posts.colaborador'),
        ),
        migrations.CreateModel(
            name='ADMINxPOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
                ('id_post_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='administrado',
            field=models.ManyToManyField(blank=True, through='posts.ADMINxPOST', to='posts.colaborador'),
        ),
        migrations.CreateModel(
            name='ADMINxUSUARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('id_colaborador_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.colaborador')),
                ('id_usuario_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='administrado',
            field=models.ManyToManyField(blank=True, through='posts.ADMINxUSUARIO', to='posts.colaborador'),
        ),
    ]
