# Generated by Django 5.1.1 on 2024-10-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_adminxcomentario_comentario_administrado_adminxpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='username',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
